### ISSUE TITLE
[Feature] Allow adding padding to imported maps

### ISSUE THREAD

**Issue by BoltsJ** [moo-man/FVTT-DD-Import#52]
It would be nice if the importer either allowed padding to be added to the maps on import, or used the foundry default ammount of padding. The lack of padding makes using hex and gridless very difficult to work with, and adding padding in the scene options after creation causes the wall to move

**Comment by Stratlin** [comment]
If you are taking requests for future updates, I'd very much like to second this request. I use the padding on maps for informative tiles like the one below and as the previous commenter posted, adding padding after the fact can be quite difficult due to it shifting already placed objects.

![image](https://user-images.githubusercontent.com/77936542/105640848-587d5180-5e4e-11eb-8cd0-fd454d1b0ddb.png)
